spring:
  application:
    name: multi-resource
  data:
    mongodb:
      db1:
        host: localhost
        port: 27017
        database: db1

      db2:
        host: localhost
        port: 27017
        database: db2
  datasource:
    mysql1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123456
    mysql2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123456
server:
  port: 8080

